"""
Step 2: Regex NER Baseline Built on a Real Lexicon
"""

import re
import json
import gzip
import argparse
from pathlib import Path
from typing import List, Tuple, Dict


# ══════════════════════════════════════════════════════════════════
# Load the lexicon and compile regex patterns
# ══════════════════════════════════════════════════════════════════

def load_lexicon(lexicon_path: str) -> dict:
    """Load the JSON lexicon generated by build_lexicon.py."""
    with open(lexicon_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    total = sum(len(v) for v in data.values())
    print(f"[Lexicon] Disease={len(data.get('Disease',[]))}, Chemical={len(data.get('Chemical',[]))}, Total={total} entries")
    return data


def build_regex_patterns(lexicon: dict) -> List[Tuple[re.Pattern, str]]:
    """
    Compile one regex pattern for each entity type.
    """
    patterns = []
    # Disease first
    for entity_type in ('Disease', 'Chemical'):
        terms = lexicon.get(entity_type, [])
        if not terms:
            continue

        # Sort in descending order (longer terms first)
        terms_sorted = sorted(terms, key=lambda t: len(t), reverse=True)

        # Escape and join into an OR expression
        escaped = [re.escape(t) for t in terms_sorted]
        combined = '|'.join(escaped)
        # (?<!\w) and (?!\w) are zero-width assertions and are more robust than \b
        # for medical terms containing hyphens
        pattern_str = r'(?<!\w)(?:' + combined + r')(?!\w)'
        compiled = re.compile(pattern_str, re.IGNORECASE)
        patterns.append((compiled, entity_type))

    return patterns


# ══════════════════════════════════════════════════════════════════
# Core recognition function
# ══════════════════════════════════════════════════════════════════

def extract_entities(text: str,
                     patterns: List[Tuple[re.Pattern, str]]) -> List[Dict]:
    """
    Scan the text with the regex lexicon and identify all Disease and Chemical entities.
    """
    entities = []
    # Keep track of occupied (start, end) spans to avoid duplication
    occupied: List[Tuple[int, int]] = []

    def overlaps(s: int, e: int) -> bool:
        return any(not (e <= os or s >= oe) for os, oe in occupied)

    for compiled, entity_type in patterns:
        for match in compiled.finditer(text):
            s, e = match.start(), match.end()
            if overlaps(s, e):
                continue
            entities.append({
                "text":  match.group(),
                "label": entity_type,
                "start": s,
                "end":   e,
            })
            occupied.append((s, e))

    entities.sort(key=lambda x: x["start"])
    return entities


def annotate_text(text: str, entities: List[Dict]) -> str:
    """
    Insert [entity/label] tags into the original text for easy visual inspection.
    Example: "Patients with [type 2 diabetes/Disease] treated with [metformin/Chemical]."
    """
    result = []
    prev = 0
    for ent in entities:
        result.append(text[prev:ent["start"]])
        result.append(f"[{ent['text']}/{ent['label']}]")
        prev = ent["end"]
    result.append(text[prev:])
    return "".join(result)


# ══════════════════════════════════════════════════════════════════
# BIO-format output (for evaluate_ner.py)
# ══════════════════════════════════════════════════════════════════

def text_to_bio(text: str, entities: List[Dict]) -> List[Tuple[str, str]]:
    """
    Map character-level entity spans to token-level BIO labels.

    Tokenization strategy: use simple whitespace tokenization
    to stay consistent with BC5CDR PubTator format.

    BIO rules:
      B-X = the first token of entity X
      I-X = the following tokens of entity X
      O   = a non-entity token
    """
    tokens = []
    offsets = []  # (start, end) for each token

    # Tokenize with regex while preserving character offsets
    for m in re.finditer(r'\S+', text):
        tokens.append(m.group())
        offsets.append((m.start(), m.end()))

    labels = ['O'] * len(tokens)

    for ent in entities:
        es, ee, etype = ent["start"], ent["end"], ent["label"]
        first = True
        for i, (ts, te) in enumerate(offsets):
            # token overlaps with the entity span
            if te > es and ts < ee:
                if first:
                    labels[i] = f'B-{etype}'
                    first = False
                else:
                    labels[i] = f'I-{etype}'

    return list(zip(tokens, labels))


# ══════════════════════════════════════════════════════════════════
# Read BC5CDR PubTator format and output BIO predictions
# ══════════════════════════════════════════════════════════════════

def process_bc5cdr_for_eval(filepath: str,
                             patterns: List[Tuple[re.Pattern, str]],
                             output_path: str,
                             show_examples: int = 10):
    """
    Read the BC5CDR test set (PubTator format), run the baseline NER on the title + abstract 
    of each article, and output BIO-format JSON for evaluate_ner.py to compute P/R/F1.

    The gold annotations are also read and written to the output file for convenient comparison.

    """
    filepath = Path(filepath)
    if not filepath.exists():
        raise FileNotFoundError(f"File not found: {filepath}")

    print(f"[Evaluation] Processing BC5CDR file: {filepath}")

    opener = gzip.open if str(filepath).endswith('.gz') else open
    ann_pattern = re.compile(
        r'^(\d+)\t(\d+)\t(\d+)\t(.+?)\t(Disease|Chemical)\t(.*)$'
    )

    results = []
    current_pmid = None
    current_title = ""
    current_abstract = ""
    gold_anns = []   # [(start, end, type), ...]

    def flush_article():
        if current_pmid is None:
            return

        full_text = current_title + " " + current_abstract
        # If offsets are computed separately for title and abstract, add the title offset
        title_len = len(current_title) + 1  # +1 for the space

        # Baseline prediction
        pred_entities = extract_entities(full_text, patterns)

        # Convert to BIO
        tokens_labels_pred = text_to_bio(full_text, pred_entities)
        tokens = [t for t, _ in tokens_labels_pred]
        pred_labels = [l for _, l in tokens_labels_pred]

        # Convert gold standard to BIO as well
        # Note: BC5CDR offsets are relative to title/abstract separately and must be adjusted
        gold_entities_merged = []
        for gs, ge, gtype in gold_anns:
            gold_entities_merged.append({
                "text": full_text[gs:ge], "label": gtype,
                "start": gs, "end": ge
            })
        tokens_labels_gold = text_to_bio(full_text, gold_entities_merged)
        gold_labels = [l for _, l in tokens_labels_gold]

        results.append({
            "pmid":         current_pmid,
            "text":         full_text,
            "annotated":    annotate_text(full_text, pred_entities),
            "pred_entities": pred_entities,
            "tokens":       tokens,
            "gold_labels":  gold_labels,
            "pred_labels":  pred_labels,
        })

    with opener(filepath, 'rt', encoding='utf-8') as f:
        for raw_line in f:
            line = raw_line.rstrip('\n')

            if not line.strip():
                # Blank line → end of article, flush the current article
                flush_article()
                current_pmid = None
                current_title = ""
                current_abstract = ""
                gold_anns = []
                continue

            # Title line
            if re.match(r'^\d+\|t\|', line):
                pmid, _, text = line.split('|', 2)
                current_pmid  = pmid
                current_title = text

            # Abstract line
            elif re.match(r'^\d+\|a\|', line):
                _, _, text = line.split('|', 2)
                current_abstract = text

            # Annotation line
            else:
                m = ann_pattern.match(line)
                if m:
                    pmid  = m.group(1)
                    start = int(m.group(2))
                    end   = int(m.group(3))
                    etype = m.group(5)
                    # BC5CDR offsets are computed separately for each passage
                    # Title passage: offsets [0, len(title))
                    # Abstract passage: offsets [0, len(abstract)), so add len(title)+1
                    title_len = len(current_title) + 1
                    if start < len(current_title):
                        # Annotation is in the title
                        adj_start = start
                        adj_end   = end
                    else:
                        # Annotation is in the abstract (offsets are relative to abstract start)
                        adj_start = start + title_len
                        adj_end   = end   + title_len
                    gold_anns.append((adj_start, adj_end, etype))

    # Process the last article (in case the file does not end with a blank line)
    flush_article()

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(results, f, ensure_ascii=False, indent=2)

    print(f"[Evaluation] Done. Processed {len(results)} articles in total. Results saved to {output_path}")
    print(f"             Then run evaluate_ner.py to compute P/R/F1:")
    print(f"             python evaluate_ner.py --file {output_path}")
    print_sample_examples(results, show_examples)
    return results


# ══════════════════════════════════════════════════════════════════
# Batch process a text file
# ══════════════════════════════════════════════════════════════════

def process_text_file(input_path: str,
                      patterns: List[Tuple[re.Pattern, str]],
                      output_path: str,
                      show_examples: int = 30):
    """
    Read a text file line by line (one abstract per line), recognize entities,
    and save the results as JSON.
    """
    results = []
    with open(input_path, 'r', encoding='utf-8') as f:
        lines = [l.strip() for l in f if l.strip()]

    for i, text in enumerate(lines):
        entities = extract_entities(text, patterns)
        results.append({
            "id":         i,
            "text":       text,
            "annotated":  annotate_text(text, entities),
            "entities":   entities,
        })

    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(results, f, ensure_ascii=False, indent=2)

    print(f"Processing complete: {len(lines)} text segments in total. Results saved to {output_path}")
    print_sample_examples(results, show_examples)
    return results

def bio_labels_to_entities(tokens: List[str], labels: List[str]) -> List[Dict]:
    """
    Convert token-level BIO labels into simple entity dictionaries.
    """
    entities = []
    i = 0
    while i < len(labels):
        tag = labels[i]
        if tag.startswith("B-"):
            entity_type = tag[2:]
            j = i + 1
            while j < len(labels) and labels[j] == f"I-{entity_type}":
                j += 1
            entities.append({
                "text": " ".join(tokens[i:j]),
                "label": entity_type,
            })
            i = j
        elif tag.startswith("I-"):
            entity_type = tag[2:]
            entities.append({
                "text": tokens[i],
                "label": entity_type,
            })
            i += 1
        else:
            i += 1
    return entities


def annotate_text_by_entity_strings(text: str, entities: List[Dict]) -> str:
    """
    Rebuild an annotated preview string from entity texts.
    This is used when results only contain BIO labels instead of character spans.
    """
    if not entities:
        return text

    annotated = text
    unique_entities = []
    seen = set()
    for ent in entities:
        key = (ent["text"], ent["label"])
        if key not in seen:
            seen.add(key)
            unique_entities.append(ent)

    unique_entities.sort(key=lambda x: len(x["text"]), reverse=True)

    for ent in unique_entities:
        ent_text = ent["text"]
        ent_label = ent["label"]
        if not ent_text.strip():
            continue
        annotated = re.sub(
            re.escape(ent_text),
            f"[{ent_text}/{ent_label}]",
            annotated,
            flags=re.IGNORECASE
        )
    return annotated


def print_sample_examples(results: List[Dict], max_examples: int = 30):
    """
    Print up to max_examples outputs in a reader-friendly format.
    """
    if not results:
        print("[Examples] No results available to display.")
        return

    print("" + "=" * 70)
    print(f"  Showing up to {min(max_examples, len(results))} example outputs")
    print("=" * 70)

    for i, item in enumerate(results[:max_examples], 1):
        text = item.get("text", "")
        entities = item.get("entities", [])

        if not entities and item.get("pred_entities"):
            entities = item["pred_entities"]

        if not entities and "tokens" in item and "pred_labels" in item:
            entities = bio_labels_to_entities(item["tokens"], item["pred_labels"])

        annotated = item.get("annotated")
        if not annotated:
            if item.get("entities"):
                annotated = annotate_text(text, item["entities"])
            elif item.get("pred_entities"):
                annotated = annotate_text(text, item["pred_entities"])
            else:
                annotated = annotate_text_by_entity_strings(text, entities)

        diseases = [e["text"] for e in entities if e["label"] == "Disease"]
        chemicals = [e["text"] for e in entities if e["label"] == "Chemical"]

        print(f"[Example {i:02d}]")
        if "pmid" in item:
            print(f"PMID      : {item['pmid']}")
        print(f"Original   : {text}")
        print(f"Annotated  : {annotated}")
        print(f"Diseases   : {diseases}")
        print(f"Chemicals  : {chemicals}")

    print("" + "=" * 70)

# ══════════════════════════════════════════════════════════════════
# Main program
# ══════════════════════════════════════════════════════════════════

def main():
    parser = argparse.ArgumentParser(
        description="Regex NER baseline built on a real medical lexicon",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python baseline_ner.py --lexicon data/lexicon.json --bc5cdr CDR_TestSet.PubTator.txt --output-bio eval_input.json
        """
    )
    parser.add_argument('--lexicon',    required=True, metavar='PATH',
                        help='Path to the lexicon JSON file generated by build_lexicon.py')
    parser.add_argument('--input',      metavar='PATH',
                        help='Input text file (one abstract per line)')
    parser.add_argument('--show-examples', type=int, default=30, metavar='N',
                        help='Number of example outputs to print (default: 30)')
    parser.add_argument('--output',     metavar='PATH', default='predictions.json',
                        help='Output JSON file path')
    parser.add_argument('--bc5cdr',     metavar='PATH',
                        help='BC5CDR PubTator file (used to generate evaluation input with gold labels)')
    parser.add_argument('--output-bio', metavar='PATH', default='eval_input.json',
                        help='Path to the BC5CDR evaluation input file (for evaluate_ner.py)')
    args = parser.parse_args()

    # Load the lexicon and compile regex patterns
    lexicon  = load_lexicon(args.lexicon)
    patterns = build_regex_patterns(lexicon)
    print(f"[Regex] Compiled {len(patterns)} patterns in total (Disease + Chemical)")


    if args.input:
        process_text_file(args.input, patterns, args.output, args.show_examples)

    if args.bc5cdr:
        process_bc5cdr_for_eval(args.bc5cdr, patterns, args.output_bio, args.show_examples)

    if not any([args.input, args.bc5cdr]):
        parser.print_help()


if __name__ == '__main__':
    main()
